version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod.env
    expose:
      - 5432

  webapp:
    build: ./webapp
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.prod.env
    volumes:
      - ./webapp:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - logs_volume:/code/logs
    depends_on:
      - db
      - redis  # Webapp зависит от Redis
    expose:
      - 8000

  celery:
    build: ./webapp
    command: celery -A webapp worker --loglevel=info
    env_file:
      - ./.prod.env
    volumes:
      - ./webapp:/code
    depends_on:
      - webapp
      - redis  # Celery зависит от Redis
    expose:
      - 8000

  celery_beat:
    build: ./webapp
    command: celery -A webapp beat --loglevel=info
    env_file:
      - ./.prod.env
    volumes:
      - ./webapp:/code
    depends_on:
      - webapp
      - redis
    expose:
      - 8000

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - webapp

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
  certs:
