# Generated by Django 4.2.15 on 2024-08-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Сумма итого')),
                ('status', models.CharField(blank=True, max_length=2, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Продажа билета',
                'verbose_name_plural': 'Продажа билетов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketSalesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.DateField(verbose_name='Время мероприятия')),
                ('inventories_count', models.PositiveSmallIntegerField(verbose_name='Количество нвентаря')),
                ('tickets_count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
                ('tickets_amount', models.IntegerField(verbose_name='Сумма билетов')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('total_amount', models.IntegerField(verbose_name='Сумма итого')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.inventory', verbose_name='Инвентарь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.ticketsale', verbose_name='Продажа билета')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TicketSalesPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('payment_method', models.CharField(choices=[('QR', 'Оплата по QR'), ('CD', 'Оплата картой'), ('CH', 'Наличка')], default='QR', max_length=2)),
                ('accepted_from_the_buyer', models.IntegerField(verbose_name='Принято от покупателя')),
                ('amount_of_change', models.IntegerField(blank=True, default=0, verbose_name='Сумма сдачи')),
                ('accepted_amount', models.IntegerField(blank=True, default=0, verbose_name='Принятая сумма')),
                ('process_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор процесса')),
                ('last_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='Последний статус')),
                ('error_text', models.CharField(blank=True, max_length=450, null=True, verbose_name='Текст ошибки')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор успешной транзакции')),
                ('response_data', models.TextField(blank=True, max_length=400, null=True, verbose_name='Полученные данные')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.ticketsale', verbose_name='Продажа билета')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['id'],
            },
        ),
    ]
