# Generated by Django 4.2.15 on 2024-09-03 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ticket_sales.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Настройки терминала',
                'verbose_name_plural': 'Настройки терминала',
            },
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Сумма итого')),
                ('paid_amount', models.IntegerField(blank=True, default=0, verbose_name='Сумма оплаты')),
                ('refund_amount', models.IntegerField(blank=True, default=0, verbose_name='Сумма возврата')),
                ('paid_cash', models.IntegerField(blank=True, default=0, verbose_name='Оплачено наличкой')),
                ('paid_card', models.IntegerField(blank=True, default=0, verbose_name='Оплачено картой')),
                ('paid_qr', models.IntegerField(blank=True, default=0, verbose_name='Оплачено QR')),
                ('status', models.CharField(blank=True, default='Новый заказ', max_length=25, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketsSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время мероприятия')),
                ('tickets_count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Проданный билет',
                'verbose_name_plural': 'Проданные билеты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketSalesTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма билета')),
                ('ticket_guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор билета')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketSalesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=ticket_sales.models.default_datetime, verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время мероприятия')),
                ('tickets_count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
                ('tickets_amount', models.IntegerField(verbose_name='Сумма билетов')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('total_amount', models.IntegerField(verbose_name='Сумма итого')),
                ('ticket_guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор билета')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketSalesPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('payment_method', models.CharField(choices=[('QR', 'Оплата по QR'), ('CD', 'Оплата картой'), ('CH', 'Наличка')], default='QR', max_length=2)),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Сумма оплаты')),
                ('process_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор процесса')),
                ('last_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='Последний статус')),
                ('error_text', models.CharField(blank=True, max_length=450, null=True, verbose_name='Текст ошибки')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор успешной транзакции')),
                ('response_data', models.TextField(blank=True, max_length=600, null=True, verbose_name='Полученные данные')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-id'],
            },
        ),
    ]
