# Generated by Django 4.2.15 on 2024-09-03 18:12

from django.db import migrations, models
import django.db.models.deletion
import ticket_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_event_begin_date_alter_event_end_date'),
        ('ticket_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketsalesticket',
            name='event_date',
            field=models.DateField(default=ticket_sales.models.default_datetime, verbose_name='Дата мероприятия'),
        ),
        migrations.AddField(
            model_name='ticketsalesticket',
            name='event_time',
            field=models.TimeField(default=None, verbose_name='Время мероприятия'),
            preserve_default=False,
        ),
    ]
