# Generated by Django 4.2.15 on 2024-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(blank=True, default='Новый заказ', max_length=25, null=True, verbose_name='Статус'),
        ),
    ]
