# Generated by Django 4.2.15 on 2024-08-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Продажа билета'),
        ),
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='event_time',
            field=models.TimeField(verbose_name='Время мероприятия'),
        ),
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Продажа билета'),
        ),
    ]
