# Generated by Django 4.2.15 on 2024-08-27 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0002_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesservice',
            name='ticket_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор билета'),
        ),
    ]
