# Generated by Django 4.2.15 on 2024-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0002_ticketsalesticket_event_ticketsalesticket_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsalesservice',
            name='ticket_guid',
        ),
        migrations.AddField(
            model_name='ticketsalesservice',
            name='event_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AddField(
            model_name='ticketsalesticket',
            name='event_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='event_time',
            field=models.TimeField(verbose_name='Время начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='ticketsalesticket',
            name='event_time',
            field=models.TimeField(verbose_name='Время начала мероприятия'),
        ),
    ]
