# Generated by Django 4.2.15 on 2024-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0003_remove_ticketsalesservice_ticket_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер билета'),
            preserve_default=False,
        ),
    ]
