# Generated by Django 4.2.15 on 2024-08-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0003_remove_ticketsalespayments_accepted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='refund_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма возврата'),
        ),
    ]
