# Generated by Django 4.2.15 on 2024-08-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_eventtimes_is_active'),
        ('ticket_sales', '0003_ticketsalesservice_ticket_guid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsalespayments',
            options={'ordering': ['-id'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='ticketsalesservice',
            options={'ordering': ['-id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.CreateModel(
            name='TicketsSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время мероприятия')),
                ('tickets_count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Проданный билет',
                'verbose_name_plural': 'Проданные билеты',
                'ordering': ['-id'],
            },
        ),
    ]
