# Generated by Django 4.2.15 on 2024-08-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0004_ticketsale_paid_amount_ticketsale_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(blank=True, default='Сформирован', max_length=2, null=True, verbose_name='Статус'),
        ),
    ]
