# Generated by Django 4.2.15 on 2024-08-29 10:59

from django.db import migrations, models
import ticket_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0004_alter_ticketsalespayments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='event_date',
            field=models.DateField(default=ticket_sales.models.default_datetime, verbose_name='Дата мероприятия'),
        ),
    ]
