# Generated by Django 4.2.15 on 2024-08-16 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0005_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
