# Generated by Django 4.2.15 on 2024-09-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0005_alter_ticketsalesticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='tickets_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Всего билетов'),
        ),
    ]
