# Generated by Django 4.2.15 on 2024-09-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0006_terminalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalsettings',
            options={'verbose_name': 'Настройки терминала'},
        ),
    ]
