# Generated by Django 4.2.15 on 2024-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0006_ticketsale_tickets_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='last_event_code',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Код последнего события'),
        ),
    ]
