# Generated by Django 4.2.15 on 2024-09-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0007_ticketsalesticket_last_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='tickets_made',
            field=models.BooleanField(blank=True, default=False, verbose_name='Билеты сформированы'),
        ),
    ]
