# Generated by Django 4.2.15 on 2024-09-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0008_ticketsale_tickets_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='terminal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Куплен в терминале'),
        ),
    ]
