# Generated by Django 4.2.15 on 2024-08-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('ticket_sales', '0008_alter_ticketsale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='inventories_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество инвентаря'),
        ),
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.inventory', verbose_name='Инвентарь'),
        ),
    ]
