# Generated by Django 4.2.15 on 2024-08-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0009_alter_ticketsalesservice_inventories_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='response_data',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Полученные данные'),
        ),
    ]
