# Generated by Django 4.2.15 on 2024-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0009_ticketsale_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsale',
            name='terminal',
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('CS', 'Касса'), ('TS', 'Киоск'), ('SM', 'Сайт muzaidyny.kz'), ('KP', 'Kaspi платежи')], default='CS', max_length=2, verbose_name='Тип продажи'),
        ),
    ]
