# Generated by Django 4.2.15 on 2024-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0009_alter_terminalsettings_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalsettings',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
