# Generated by Django 4.2.15 on 2024-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0010_alter_ticketsalespayments_response_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(blank=True, default='Сформирован', max_length=25, null=True, verbose_name='Статус'),
        ),
    ]
