# Generated by Django 4.2.15 on 2024-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0010_remove_ticketsale_terminal_ticketsale_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(blank=True, choices=[('NP', 'Не оплачен'), ('PD', 'Оплачен'), ('PP', 'Частично оплачен'), ('RT', 'Возврат'), ('CN', 'Отменен')], default='NP', max_length=2, null=True, verbose_name='Статус'),
        ),
    ]
