# Generated by Django 4.2.15 on 2024-09-03 00:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_service_on_calculation'),
        ('ticket_sales', '0010_alter_terminalsettings_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSalesTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма билета')),
                ('ticket_guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор билета')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-id'],
            },
        ),
    ]
