# Generated by Django 4.2.15 on 2024-09-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0011_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsale',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
