# Generated by Django 4.2.15 on 2024-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0011_ticketsalesticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='process_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор процесса'),
        ),
    ]
