# Generated by Django 4.2.15 on 2024-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0011_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='paid_card',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оплачено картой'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='paid_cash',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оплачено наличкой'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='paid_qr',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оплачено QR'),
        ),
    ]
