# Generated by Django 4.2.15 on 2024-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0012_alter_ticketsale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='app_type',
            field=models.CharField(blank=True, choices=[('CS', 'Касса'), ('TS', 'Киоск'), ('SM', 'Сайт muzaidyny.kz'), ('KP', 'Kaspi платежи')], default='CS', max_length=2, null=True, unique=True, verbose_name='Тип приложения'),
        ),
    ]
