# Generated by Django 4.2.15 on 2024-08-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0012_ticketsale_paid_card_ticketsale_paid_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsalesservice',
            name='inventories_count',
        ),
        migrations.RemoveField(
            model_name='ticketsalesservice',
            name='inventory',
        ),
    ]
