# Generated by Django 4.2.15 on 2024-08-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0013_remove_ticketsalesservice_inventories_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsale',
            options={'ordering': ['-date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='ticketsalesservice',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.ticketsale', verbose_name='Заказ'),
        ),
    ]
