# Generated by Django 4.2.15 on 2024-09-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0014_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='booking_begin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата время бронирования'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='booking_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата время окончания бронирования'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
