# Generated by Django 4.2.15 on 2024-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0015_ticketsale_booking_begin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='is_refund',
            field=models.BooleanField(default=False, verbose_name='Возвратный'),
        ),
    ]
