# Generated by Django 4.2.15 on 2024-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0016_ticketsalesticket_is_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('QR', 'Оплата по QR'), ('CD', 'Оплата картой'), ('CH', 'Наличка')], default='QR', max_length=2, null=True),
        ),
    ]
