# Generated by Django 4.2.15 on 2024-09-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0017_ticketsalesticket_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsalesticket',
            name='payment_method',
        ),
    ]
