# Generated by Django 4.2.15 on 2024-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0018_remove_ticketsalesticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalespayments',
            name='refund_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='ticketsalesticket',
            name='last_event_code',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Код последнего события'),
        ),
    ]
