# Generated by Django 4.2.15 on 2024-09-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0019_ticketsalespayments_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.ticketsalespayments', verbose_name='Платеж'),
        ),
    ]
