# Generated by Django 4.2.15 on 2024-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0020_ticketsalesticket_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesservice',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма оплачено'),
        ),
    ]
