# Generated by Django 4.2.15 on 2024-09-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0021_ticketsalesservice_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalespayments',
            name='card_mask',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='ticketsalespayments',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='ticketsalespayments',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='ticketsalespayments',
            name='terminal',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Валюта'),
        ),
    ]
