# Generated by Django 4.2.15 on 2024-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0022_ticketsalespayments_card_mask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='card_mask',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Маска карты'),
        ),
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='terminal',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='ID терминала'),
        ),
    ]
