# Generated by Django 4.2.15 on 2024-09-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0023_alter_ticketsalespayments_card_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalespayments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
