# Generated by Django 4.2.15 on 2024-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0024_ticketsalespayments_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор успешной транзакции'),
        ),
    ]
