# Generated by Django 4.2.15 on 2024-09-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0025_alter_ticketsalespayments_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalespayments',
            name='response_data',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Полученные данные'),
        ),
    ]
