# Generated by Django 4.2.15 on 2024-09-25 05:12

from django.db import migrations, models
import django.db.models.deletion
import ticket_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_event_options_alter_eventtemplate_options'),
        ('ticket_sales', '0026_alter_ticketsalespayments_response_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSalesBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=ticket_sales.models.default_datetime, verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время начала мероприятия')),
                ('event_time_end', models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия')),
                ('tickets_count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
                ('tickets_amount', models.IntegerField(verbose_name='Сумма билетов')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('total_amount', models.IntegerField(verbose_name='Сумма итого')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.event', verbose_name='Мероприятие')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Бронь места',
                'verbose_name_plural': 'Бронирование мест',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='TicketsSold',
        ),
    ]
