# Generated by Django 4.2.15 on 2024-09-25 11:43

from django.db import migrations, models
import ticket_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0027_ticketsalesbooking_delete_ticketssold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesbooking',
            name='created_date',
            field=models.DateField(default=ticket_sales.models.default_datetime, verbose_name='Дата создания'),
        ),
    ]
