# Generated by Django 4.2.15 on 2024-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0028_ticketsalesbooking_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalesbooking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
