# Generated by Django 4.2.15 on 2024-09-26 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0030_ticketsalesbooking_booking_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='booking_guid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='GUID бронирования'),
        ),
    ]
