# Generated by Django 4.2.15 on 2024-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0031_ticketsale_booking_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='booking_guid',
            field=models.UUIDField(blank=True, verbose_name='GUID бронирования'),
        ),
        migrations.AlterField(
            model_name='ticketsalesbooking',
            name='booking_guid',
            field=models.UUIDField(blank=True, verbose_name='GUID бронирования'),
        ),
    ]
