# Generated by Django 4.2.15 on 2024-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0032_alter_ticketsale_booking_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='process_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор процесса'),
        ),
    ]
