# Generated by Django 4.2.15 on 2024-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0035_alter_ticketsalesticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='port',
            field=models.CharField(default='8080', max_length=7, verbose_name='Port (8080)'),
        ),
    ]
