# Generated by Django 4.2.15 on 2024-10-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0036_terminalsettings_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalsettings',
            options={'verbose_name': 'Настройки терминала', 'verbose_name_plural': 'Настройки терминалов'},
        ),
        migrations.AlterModelOptions(
            name='ticketsalespayments',
            options={'ordering': ['-id'], 'verbose_name': 'Платеж заказа', 'verbose_name_plural': 'Платежи заказов'},
        ),
        migrations.AlterModelOptions(
            name='ticketsalesservice',
            options={'ordering': ['-id'], 'verbose_name': 'Услуга заказа', 'verbose_name_plural': 'Услуги заказов'},
        ),
        migrations.AlterModelOptions(
            name='ticketsalesticket',
            options={'ordering': ['number'], 'verbose_name': 'Билет в заказе', 'verbose_name_plural': 'Билеты в заказах'},
        ),
    ]
