# Generated by Django 4.2.15 on 2024-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0037_alter_terminalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesticket',
            name='refund_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма возврата'),
        ),
    ]
