# Generated by Django 4.2.15 on 2024-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0039_alter_ticketsale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='use_https',
            field=models.BooleanField(default=False, null=True, verbose_name='Use https'),
        ),
    ]
