# Generated by Django 4.2.15 on 2024-10-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0041_ticketsalespayments_refund_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_immediately', models.BooleanField(default=False, verbose_name='В киоске печать сразу отправлять на принтер')),
                ('minutes_before', models.PositiveSmallIntegerField(default=0, verbose_name='Допустимое количество минут до начала сеанса')),
                ('minutes_after', models.PositiveSmallIntegerField(default=0, verbose_name='Допустимое количество минут после окончания сеанса')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
    ]
