# Generated by Django 4.2.15 on 2024-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0042_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='minutes_after',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Допустимое количество минут после окончания сеанса'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='minutes_before',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Допустимое количество минут до начала сеанса'),
        ),
    ]
