# Generated by Django 4.2.15 on 2024-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0045_ticketsalesticket_activated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='full_exit_after_min',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Количество минут для свободного выхода после завершения сеанса'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='full_exit_before_min',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Количество минут для свободного выхода до завершения сеанса'),
        ),
    ]
