# Generated by Django 4.2.15 on 2024-09-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketsReport',
            new_name='Reports',
        ),
    ]
