# Generated by Django 4.2.15 on 2024-09-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_ticketsreport_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'permissions': [('view_sales_report', 'Может просматривать отчет по продажам'), ('view_events_report', 'Может просматривать отчет по сеансам'), ('view_tickets_report', 'Может просматривать отчет реестр билетов')]},
        ),
    ]
