# Generated by Django 4.2.15 on 2024-10-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reports_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'permissions': [('view_sales_report', 'Может просматривать отчет по продажам'), ('view_events_report', 'Может просматривать отчет по сеансам'), ('view_tickets_report', 'Может просматривать отчет реестр билетов'), ('access_available_event_dates', 'Доступ к методу available-event-dates'), ('access_events_list', 'Доступ к методу events-list'), ('access_services_list', 'Доступ к методу services-list'), ('access_ticket_check', 'Доступ к методу ticket-check'), ('access_create_tickets', 'Доступ к методу create-tickets'), ('access_payment_info', 'Доступ к методу payment-info'), ('access_cs_app', 'Доступ к приложению Касса'), ('access_ts_app', 'Доступ к приложению Кисок'), ('access_sm_app', 'Доступ к приложению Сайт muzaidyny.kz'), ('access_kp_app', 'Доступ к приложению Kaspi')]},
        ),
    ]
