# Generated by Django 5.0.7 on 2024-07-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Наименование (рус.)')),
                ('name_kz', models.CharField(max_length=200, verbose_name='Наименование (каз.)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Наименование (анг.)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (рус.)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Заголовок (каз.)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (анг.)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Содержание (рус.)')),
                ('content_kz', models.TextField(blank=True, verbose_name='Содержание (каз.)')),
                ('content_en', models.TextField(blank=True, verbose_name='Содержание (анг.)')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка анонса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('published', models.BooleanField(blank=True, default=False, verbose_name='Опубликован')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='news_image/%Y/%m/%d', verbose_name='Картинка')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Картинку для этой новости',
                'verbose_name_plural': 'Картинки для этой новости',
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug', '-created_at'], name='news_news_slug_b1e55f_idx'),
        ),
    ]
