# Generated by Django 4.2.15 on 2024-10-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, verbose_name='Идентификатор записи')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('deleted', 'Удаление')], max_length=10, verbose_name='Тип события')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Измененные данные')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия записи')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время события')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменений записи',
                'verbose_name_plural': 'Логи изменений записей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
