# Generated by Django 4.2.15 on 2024-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordchangelog',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название таблицы'),
        ),
    ]
