# Generated by Django 4.2.15 on 2024-08-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('on_monday', models.BooleanField(verbose_name='Понедельник')),
                ('on_tuesday', models.BooleanField(verbose_name='Вторник')),
                ('on_wednesday', models.BooleanField(verbose_name='Среда')),
                ('on_thursday', models.BooleanField(verbose_name='Четверг')),
                ('on_friday', models.BooleanField(verbose_name='Пятница')),
                ('on_saturday', models.BooleanField(verbose_name='Суббота')),
                ('on_sunday', models.BooleanField(verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-begin_date'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон мероприятий',
                'verbose_name_plural': 'Шаблоны мероприятии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('size', models.CharField(max_length=15, verbose_name='Размер')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.inventory', verbose_name='Инвентарь')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.TimeField(verbose_name='Дата начала')),
                ('end_date', models.TimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(verbose_name='Активность')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplateServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.eventtemplate', verbose_name='Шаблон мероприятий')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.eventtemplate', verbose_name='Шаблон мероприятий'),
        ),
    ]
