# Generated by Django 4.2.15 on 2024-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество билетов'),
        ),
    ]
