# Generated by Django 4.2.15 on 2024-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_event_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
