# Generated by Django 4.2.15 on 2024-09-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_event_begin_date_alter_event_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-begin_date'], 'verbose_name': 'Сеанс мероприятия', 'verbose_name_plural': 'Сеансы мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
