# Generated by Django 4.2.15 on 2024-09-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_eventtimes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='on_calculation',
            field=models.BooleanField(default=False, verbose_name='Учитывать в подсчете билетов'),
        ),
    ]
