# Generated by Django 4.2.15 on 2024-10-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_saletype_service_sale_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplateservices',
            options={'verbose_name': 'Услуга в мероприятии', 'verbose_name_plural': 'Услуги в мероприи'},
        ),
        migrations.AlterField(
            model_name='eventtemplateservices',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.eventtemplate', verbose_name='Мероприятие'),
        ),
        migrations.AddConstraint(
            model_name='eventtemplateservices',
            constraint=models.UniqueConstraint(fields=('event_template', 'service'), name='unique_service_per_event_template'),
        ),
    ]
