# Generated by Django 4.2.15 on 2024-10-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_eventtemplateservices_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplateservices',
            options={'verbose_name': 'Услуга в мероприятии', 'verbose_name_plural': 'Услуги в мероприятиях'},
        ),
        migrations.AlterModelOptions(
            name='eventtimes',
            options={'ordering': ['begin_date'], 'verbose_name': 'Время сеанса мероприятия', 'verbose_name_plural': 'Время сеансов мероприятий'},
        ),
    ]
